import { Routes } from '@angular/router';
import { SchoolsDashboardComponent } from './schools-dashboard/schools-dashboard';
import { StudentsComponent } from './schools/students/students';
import { TeachersComponent } from './schools/teachers/teachers';
import { ClassesComponent } from './schools/classes/classes';
import { AttendanceComponent } from './features/attendance/attendance';
import { FeesComponent } from './features/fees/fees';
import { TimetableComponent } from './features/timetable/timetable';
import { ExamsComponent } from './features/exams/exams';
import { AdmissionsComponent } from './features/admissions/admissions';
import { BehaviorComponent } from './features/behavior/behavior';
import { AnnouncementsComponent } from './features/announcements/announcements';
import { LibraryComponent } from './features/library/library';
import { TransportComponent } from './features/transport/transport';
import { ClubsComponent } from './features/clubs/clubs';
import { ParentsComponent } from './features/parents/parents';

export const routes: Routes = [
  { path: '', component: SchoolsDashboardComponent },
  { path: 'dashboard', component: SchoolsDashboardComponent },
  { path: 'admissions', component: AdmissionsComponent },
  { path: 'students', component: StudentsComponent },
  { path: 'teachers', component: TeachersComponent },
  { path: 'classes', component: ClassesComponent },
  { path: 'attendance', component: AttendanceComponent },
  { path: 'fees', component: FeesComponent },
  { path: 'timetable', component: TimetableComponent },
  { path: 'exams', component: ExamsComponent },
  { path: 'behavior', component: BehaviorComponent },
  { path: 'announcements', component: AnnouncementsComponent },
  { path: 'library', component: LibraryComponent },
  { path: 'transport', component: TransportComponent },
  { path: 'clubs', component: ClubsComponent },
  { path: 'parents', component: ParentsComponent },
  { path: '**', redirectTo: '' }
];
